image: clfoundation/sbcl

# stages:
  # - test
  # - build

before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  # Enable Quicklisp.
  - QUICKLISP_ADD_TO_INIT_FILE=true /usr/local/bin/install-quicklisp
  # Upgrade ASDF (UIOP) to 3.3.5 because we want package-local-nicknames (from 2022).
  - mkdir -p ~/common-lisp/asdf/
  - ( cd ~/common-lisp/ && wget https://asdf.common-lisp.dev/archives/asdf-3.3.5.tar.gz  && tar -xvf asdf-3.3.5.tar.gz && mv asdf-3.3.5 asdf )
  - echo "Content of ~/common-lisp/asdf/:" && ls ~/common-lisp/asdf/
  # Install missing libraries in quicklisp/local-projects
  - make deps

build:
  stage: build
  only:
    # Only when a new tag is pushed.
    - tags
  script:
    - make build
  artifacts:
    paths:
      # Include the version number ?
      - abstock
